### ISSUE TITLE
Terminal 0.4 moves profiles.json to LocalState, Find-MSTerminalFolder should try that first now

### ISSUE THREAD

**Issue by JustinGrote** [gpduck/MSTerminalSettings#35]
Find-MSTerminalFolder should look for localstate profiles.json first, and if that throws a NotFound exception, catch it and look at remotestate (for backwards compatibility)

**Comment by arnydo** [comment]
#34 Should address this.

**Comment by JustinGrote** [comment]
Fixed #34
