### ISSUE TITLE
Looks like MakeDefault doesn't do anything?

### ISSUE THREAD

**Issue by Jaykul** [gpduck/MSTerminalSettings#36]
I can't just try the module because of the path issue in #35 ... but it looks like the `MakeDefault` switch in `Set-MSTerminalProfile` doesn't do anything?

https://github.com/gpduck/MSTerminalSettings/blob/preview/src/ExportedFunctions/Set-MSTerminalProfile.ps1

**Comment by gpduck** [comment]
Yeah looks like it.

There's a build on [appveyor](https://ci.appveyor.com/project/gpduck/msterminalsettings/builds/27209072/artifacts) for the latest PR.  I need to get it merged and released for real...

**Comment by jhoneill** [comment]
Ha, I've just been plating with this and put my own code in for it  :-) Maybe I don't need to send a PR with that, and just wait for the update.

**Comment by gpduck** [comment]
This is fixed in the latest preview release on the gallery.
