### ISSUE TITLE
ConvertFrom-Json : Invalid JSON primitive: .

### ISSUE THREAD

**Issue by andtii** [gpduck/MSTerminalSettings#51]
I deleted my profiles.json then tried to run all cmds but get the error below. Any ideas?

![image](https://user-images.githubusercontent.com/1434571/70522483-7d770e00-1b41-11ea-80c2-1b7a224d0ece.png)

**Comment by gpduck** [comment]
Can you try updating to the latest preview version? (It should go up to 1.1.54) I think Terminal is adding comments into the JSON now and the older module versions can't handle it.

```
Update-Module MSTerminalSettings -AllowPrerelease
```

**Comment by andtii** [comment]
Get this error
![image](https://user-images.githubusercontent.com/1434571/70603361-ac9b8700-1bf6-11ea-927c-0549452d6f64.png)

**Comment by andtii** [comment]
I found the issue, updated PowershellGet and restarted and now it works with latest. Thnx for awesome stuff :)
